// SNR V3 data layer — Postgres (V2 used the synchronous node:sqlite API).
// getDb() returns an async client whose shape mirrors node:sqlite; see client.ts.
import crypto from 'crypto';
import logger from '../lib/logger.js';
import { readSecret } from '../lib/secrets.js';
import { getDb, closeDb } from './client.js';
import { runMigrations } from './migrate.js';

export { getDb, closeDb };

/**
 * Initialize the database on startup: apply migrations, purge expired
 * soft-deleted sessions, and seed default settings. Replaces the synchronous
 * schema bootstrap that node:sqlite did inside getDb().
 */
export async function initDb(): Promise<void> {
  await runMigrations();
  await purgeExpiredSessions();
  await seedDefaultSettings();
}

// ── Purge soft-deleted sessions past the retention window (7 days) ───────────
async function purgeExpiredSessions(): Promise<void> {
  const db = getDb();
  try {
    const cutoff = Date.now() - 7 * 24 * 60 * 60 * 1000;
    const stale = (await db
      .prepare('SELECT id FROM sessions WHERE deleted_at IS NOT NULL AND deleted_at < ?')
      .all(cutoff)) as Array<{ id: string }>;
    for (const { id } of stale) {
      // session_inputs / analysis_results / analyst_notes cascade via FK, but
      // delete explicitly to match V2 behavior exactly.
      await db.prepare('DELETE FROM session_inputs WHERE session_id = ?').run(id);
      await db.prepare('DELETE FROM analysis_results WHERE session_id = ?').run(id);
      await db.prepare('DELETE FROM analyst_notes WHERE session_id = ?').run(id);
      await db.prepare('DELETE FROM sessions WHERE id = ?').run(id);
    }
    if (stale.length > 0) {
      logger.info(`Purged ${stale.length} soft-deleted session(s) past 7-day retention`);
    }
  } catch (err) {
    logger.warn({ err }, 'Session purge skipped (best-effort)');
  }
}

// ── Seed default settings if not present ─────────────────────────────────────
async function seedDefaultSettings(): Promise<void> {
  const db = getDb();
  const defaults: Record<string, string> = {
    org_name: process.env.ANALYST_ORG ?? 'Security Operations',
    analyst_name: process.env.ANALYST_NAME ?? 'CTI Analyst',
    analyst_email: process.env.ANALYST_EMAIL ?? 'cti-analyst@organization.com',
    default_tlp: 'AMBER',
    email_header_text: 'SIGNAL TO NOISE',
    email_footer_text:
      "This brief was generated by SNR (Signal-to-Noise). Handle per your organization’s data classification policy.",
    email_signature: '',
    email_custom_preamble: '',
    email_font_family: 'Arial',
    email_body_font_size: '14',
    cc_purple_team: '',
    cc_soc: '',
    cc_red_team: '',
    cc_dr: '',
    cc_general: '',
    custom_intro_purple_team: '',
    custom_intro_soc: '',
    custom_intro_red_team: '',
    custom_intro_dr: '',
    custom_intro_general: '',
    org_evaluation_criteria: '',
    org_detection_context: '',
    // Editable audience prompt overrides (empty = use built-in default)
    audience_prompt_purple_team: '',
    audience_prompt_soc: '',
    audience_prompt_red_team: '',
    audience_prompt_dr: '',
    audience_prompt_general: '',
    // Prompt engineering overrides (empty = use built-in defaults)
    system_prompt_override: '',
    phase1_instructions_override: '',
    phase2_template_override: '',
    // Custom audience definitions (JSON array of {id, label, prompt})
    custom_audiences: '',
    // Email section visibility toggles
    email_show_observations: 'true',
    email_show_techniques: 'true',
    email_show_affected_assets: 'true',
    email_show_actions: 'true',
    email_show_iocs: 'true',
    email_show_next_steps: 'true',
    // Branding
    email_primary_color: '#1d4ed8',
    email_secondary_color: '#0a0f1e',
    email_logo_data: '',
    // Email body layout template (empty = use built-in DEFAULT_EMAIL_TEMPLATE)
    email_template: '',
    // CTI Report template (empty = use built-in DEFAULT_REPORT_TEMPLATE)
    report_template: '',
    // LLM Provider configuration
    llm_provider: 'anthropic', // 'anthropic' | 'openai-compatible'
    api_base_url: '', // e.g. http://localhost:11434/v1 for Ollama
    api_key: '', // provider API key; falls back to ANTHROPIC_API_KEY env var
    model_name: '', // e.g. llama3.2; falls back to CLAUDE_MODEL env var
    // Detection-as-code (GitHub) publishing target. dac_github_token is masked
    // to the frontend by the sensitive-key filter (matches /token/).
    dac_github_repo: '', // owner/repo
    dac_github_branch: '', // base branch (default 'main' when empty)
    dac_github_token: '', // GitHub PAT with repo scope
    dac_path_prefix: '', // folder root for rules/reports (default 'detections')
  };
  const now = Date.now();
  for (const [key, value] of Object.entries(defaults)) {
    await db
      .prepare(
        'INSERT INTO settings (key, value, updated_at) VALUES (?, ?, ?) ON CONFLICT (key) DO NOTHING'
      )
      .run(key, value, now);
  }
}

// ── Bootstrap admin ────────────────────────────────────────────────────────

/**
 * Create the initial admin user and default team on first run.
 * Called from server startup. Idempotent — skips if users already exist.
 * Returns true if bootstrap was performed.
 */
export async function bootstrapAdmin(): Promise<boolean> {
  const db = getDb();
  const userCount = ((await db.prepare('SELECT COUNT(*) as c FROM users').get()) as { c: number }).c;
  if (userCount > 0) return false;

  const email = readSecret('A2N_ADMIN_EMAIL');
  const password = readSecret('A2N_ADMIN_PASSWORD');
  const displayName = process.env.ANALYST_NAME || 'Admin';

  if (!email || !password) {
    logger.warn('\n⚠  No users exist and A2N_ADMIN_EMAIL / A2N_ADMIN_PASSWORD are not set.');
    logger.warn('   Set these in your .env file to create the initial SNR admin account.\n');
    return false;
  }

  // Lazy-import to avoid circular dependency at module load time
  const { hashPassword, validatePasswordStrength } = await import('../lib/auth-utils.js');

  // Validate admin password meets complexity requirements
  const pwCheck = validatePasswordStrength(password);
  if (!pwCheck.valid) {
    logger.error(`\n✗ Admin password does not meet complexity requirements:`);
    for (const err of pwCheck.errors) logger.error(`  - ${err}`);
    logger.error('  Update A2N_ADMIN_PASSWORD in .env and restart SNR.\n');
    return false;
  }

  const now = Date.now();
  const adminId = crypto.randomUUID();
  const teamId = crypto.randomUUID();
  const passwordHash = await hashPassword(password);

  // Create admin user
  await db
    .prepare(
      `INSERT INTO users (id, email, password_hash, display_name, role, created_at, updated_at)
       VALUES (?, ?, ?, ?, 'admin', ?, ?)`
    )
    .run(adminId, email.toLowerCase(), passwordHash, displayName, now, now);

  // Create default team
  await db
    .prepare(
      `INSERT INTO teams (id, name, description, created_at, updated_at)
       VALUES (?, 'Default Team', 'Auto-created during initial setup', ?, ?)`
    )
    .run(teamId, now, now);

  // Add admin as team lead
  await db
    .prepare(
      `INSERT INTO team_members (team_id, user_id, role, joined_at)
       VALUES (?, ?, 'lead', ?)`
    )
    .run(teamId, adminId, now);

  // Migrate existing sessions to the default team
  await db
    .prepare('UPDATE sessions SET team_id = ?, created_by = ? WHERE team_id IS NULL')
    .run(teamId, adminId);

  // Migrate existing audit log entries
  await db.prepare('UPDATE audit_log SET user_id = ? WHERE user_id IS NULL').run(adminId);

  logger.info(`✓ Admin account created: ${email}`);
  logger.info(`✓ Default Team created. All existing sessions assigned.`);

  return true;
}

// ── Settings helpers ───────────────────────────────────────────────────────

// Small in-process cache for merged settings. Settings change rarely (admin
// actions) but are read on every analyze/export/preview, so a short TTL plus
// explicit invalidation on write avoids two DB round-trips per read. Callers get
// a fresh shallow copy so they can't mutate the cached object.
const SETTINGS_TTL_MS = parseInt(process.env.SETTINGS_CACHE_TTL_MS ?? '30000', 10);
const settingsCache = new Map<string, { value: Record<string, string>; exp: number }>();

/** Clear the merged-settings cache (call after any settings write). */
export function invalidateSettingsCache(): void {
  settingsCache.clear();
}

/**
 * Load settings with team-level overrides merged on top of org defaults.
 * If teamId is empty/undefined, returns only global settings.
 */
export async function loadMergedSettings(teamId?: string): Promise<Record<string, string>> {
  const cacheKey = teamId || '__global__';
  const cached = settingsCache.get(cacheKey);
  if (cached && cached.exp > Date.now()) return { ...cached.value };

  const db = getDb();

  // Global (org-wide) settings
  const globalRows = (await db.prepare('SELECT key, value FROM settings').all()) as Array<{
    key: string;
    value: string;
  }>;
  const merged: Record<string, string> = {};
  for (const r of globalRows) merged[r.key] = r.value;

  // Overlay team-specific settings if teamId provided
  if (teamId) {
    const teamRows = (await db
      .prepare('SELECT key, value FROM team_settings WHERE team_id = ?')
      .all(teamId)) as Array<{ key: string; value: string }>;
    for (const r of teamRows) merged[r.key] = r.value;
  }

  settingsCache.set(cacheKey, { value: merged, exp: Date.now() + SETTINGS_TTL_MS });
  return { ...merged };
}

// ── Audit log ──────────────────────────────────────────────────────────────

/**
 * Append an audit-log entry. Best-effort and self-contained: errors are caught
 * and logged rather than thrown, so callers may invoke without awaiting (the
 * append still completes). The audit log is append-only.
 */
export async function appendAuditLog(entry: {
  analyst_name: string;
  user_id?: string;
  session_id?: string;
  action: string;
  input_hash?: string;
  outputs_generated?: string[];
  techniques_identified?: string[];
  details?: string;
}): Promise<void> {
  try {
    const db = getDb();
    await db
      .prepare(
        `INSERT INTO audit_log (timestamp, analyst_name, user_id, session_id, action, input_hash, outputs_generated, techniques_identified, details)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`
      )
      .run(
        Date.now(),
        entry.analyst_name,
        entry.user_id ?? null,
        entry.session_id ?? null,
        entry.action,
        entry.input_hash ?? null,
        entry.outputs_generated ? JSON.stringify(entry.outputs_generated) : null,
        entry.techniques_identified ? JSON.stringify(entry.techniques_identified) : null,
        entry.details ?? null
      );
  } catch (err) {
    logger.error({ err, action: entry.action }, 'Failed to append audit-log entry');
  }
}
