/**
 * Detection-as-code publisher: opens (or updates) a GitHub pull request containing
 * a session's generated detection rules (Sigma/YARA/Suricata, foldered by type)
 * and its Markdown report. Idempotent — re-publishing a session pushes to the same
 * per-session branch and reuses the open PR rather than creating duplicates.
 */
import { Octokit } from '@octokit/rest';
import type { AnalysisResult } from '../claude.js';

export interface DacConfig {
  owner: string;
  repo: string;
  branch: string; // base branch
  token: string;
  pathPrefix: string;
}

export interface PublishResult {
  prUrl: string;
  prNumber: number;
  branch: string;
  files: string[];
  updated: boolean;
}

/** Build a DaC config from team settings, or null if not configured. */
export function parseDacConfig(settings: Record<string, string>): DacConfig | null {
  const repoFull = settings.dac_github_repo?.trim();
  const token = settings.dac_github_token?.trim();
  if (!repoFull || !token || !repoFull.includes('/')) return null;
  const [owner, repo] = repoFull.split('/');
  if (!owner || !repo) return null;
  return {
    owner,
    repo,
    token,
    branch: settings.dac_github_branch?.trim() || 'main',
    pathPrefix: (settings.dac_path_prefix?.trim() || 'detections').replace(/^\/+|\/+$/g, ''),
  };
}

const EXT: Record<string, string> = { sigma: 'yml', yara: 'yar', suricata: 'rules' };

function slug(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'item'
  );
}

interface PublishFile {
  path: string;
  content: string;
}

export function buildFiles(
  result: AnalysisResult,
  markdownReport: string,
  sessionSlug: string,
  shortId: string,
  prefix: string,
): PublishFile[] {
  const files: PublishFile[] = [];
  const used = new Set<string>();

  for (const rule of result.detection_rules ?? []) {
    const type = (rule.rule_type || '').toLowerCase();
    const ext = EXT[type];
    if (!ext || !rule.rule_content?.trim()) continue;
    let base = `${prefix}/${type}/${slug(rule.rule_name || 'rule')}`;
    let path = `${base}.${ext}`;
    let n = 2;
    while (used.has(path)) path = `${base}-${n++}.${ext}`;
    used.add(path);
    const header = `# Source: SNR (Signal-to-Noise) · session ${shortId}\n# ${rule.rule_name}\n# ${rule.description ?? ''}\n`;
    files.push({ path, content: `${header}\n${rule.rule_content.trim()}\n` });
  }

  files.push({ path: `${prefix}/reports/${sessionSlug}-${shortId}.md`, content: markdownReport });
  return files;
}

export async function publishSession(input: {
  session: { id: string; name: string };
  result: AnalysisResult;
  markdownReport: string;
  config: DacConfig;
  sessionUrl?: string;
}): Promise<PublishResult> {
  const { config } = input;
  const octokit = new Octokit({ auth: config.token });
  const { owner, repo } = config;
  const shortId = input.session.id.slice(0, 8);
  const sessionSlug = slug(input.session.name);
  const branch = `snr/${sessionSlug}-${shortId}`;

  const files = buildFiles(input.result, input.markdownReport, sessionSlug, shortId, config.pathPrefix);
  if (files.length === 0) throw new Error('No detection rules or report to publish');

  // Resolve base branch head.
  const baseRef = await octokit.git.getRef({ owner, repo, ref: `heads/${config.branch}` });
  const baseSha = baseRef.data.object.sha;

  // Create the per-session branch if it doesn't exist yet.
  let branchExisted = true;
  try {
    await octokit.git.getRef({ owner, repo, ref: `heads/${branch}` });
  } catch {
    branchExisted = false;
    await octokit.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: baseSha });
  }

  // Commit each file (create or update — idempotent via existing blob sha).
  for (const f of files) {
    let sha: string | undefined;
    try {
      const existing = await octokit.repos.getContent({ owner, repo, path: f.path, ref: branch });
      if (!Array.isArray(existing.data) && 'sha' in existing.data) sha = existing.data.sha;
    } catch {
      /* file doesn't exist yet */
    }
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: f.path,
      branch,
      message: `SNR: ${sha ? 'update' : 'add'} ${f.path}`,
      content: Buffer.from(f.content, 'utf8').toString('base64'),
      sha,
    });
  }

  // Find an existing open PR for this branch, else open one.
  const open = await octokit.pulls.list({ owner, repo, head: `${owner}:${branch}`, state: 'open' });
  let prUrl: string;
  let prNumber: number;
  let updated = false;
  if (open.data.length > 0) {
    prUrl = open.data[0].html_url;
    prNumber = open.data[0].number;
    updated = true;
  } else {
    const body = [
      `Detections generated by **SNR (Signal-to-Noise)** for session **${input.session.name}**.`,
      '',
      input.sessionUrl ? `Session: ${input.sessionUrl}` : '',
      '',
      'Files:',
      ...files.map((f) => `- \`${f.path}\``),
    ]
      .filter((l) => l !== undefined)
      .join('\n');
    const pr = await octokit.pulls.create({
      owner,
      repo,
      head: branch,
      base: config.branch,
      title: `SNR detections: ${input.session.name}`.slice(0, 120),
      body,
    });
    prUrl = pr.data.html_url;
    prNumber = pr.data.number;
    updated = branchExisted;
  }

  return { prUrl, prNumber, branch, files: files.map((f) => f.path), updated };
}
